version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12 # Use the Python version matching your Lambda runtime
    commands:
      - echo Installing dependencies...
      - pip install --upgrade pip
      - pip install --upgrade awscli aws-sam-cli
      - pip install -r requirements.txt -t src/

  build:
    commands:
      - echo Building and packaging the SAM application...
      - sam build
      - sam package --s3-bucket myai4-deployment-artifacts --output-template-file packaged-template.yaml
      - echo Deploying the packaged application...
      - sam deploy --template-file packaged-template.yaml --stack-name myai4-backend-dev --parameter-overrides Environment=dev --capabilities CAPABILITY_NAMED_IAM --no-confirm-changeset


  post_build:
    commands:
      - echo Deployment completed
      #- pytest local_testing/ --junitxml=report.xml # Run tests and generate a report

artifacts:
  files:
    - packaged-template.yaml
    - .aws-sam/** # Include all SAM build artifacts
    #- report.xml # Include test report for visibility in CodeBuild
  discard-paths: no # Preserve the directory structure for deployment

cache:
  paths:
    - .aws-sam/cache/** # Cache SAM build artifacts for faster builds
    - .pip_cache/** # Cache Python dependencies