# yaml-language-server: disable
Transform: AWS::Serverless-2016-10-31

Resources:
  CentralizedApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_handler.lambda_handler
      Runtime: python3.12
      CodeUri: .
      MemorySize: 128
      Timeout: 10
      Environment:
        Variables:
          RAPIDAPI_KEY: !Ref RapidApiKeyParameter

Policies:
  - SSMParameterReadPolicy:
      ParameterName: "/RapidApiKeyParameter"

Parameters:
  RapidApiKeyParameter:
    Type: String
    Description: RapidAPI Key stored in AWS SSM Parameter Store